apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    run: simple-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: simple-app
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: chzbrgr71/simple-app
        ports:
          - containerPort: 5000